language: java
sudo: true
dist: trusty
jdk: oraclejdk9
services:
  - postgresql
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install:
  - chmod +x mvnw
before_script:
  - psql -c 'create database produtos-apirest;' -U postgres
